### ISSUE TITLE
Lösung für interne Link

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#11]
## Das Problem

Wir wollen aus einem Quellverzeichnis mit den .md-Dateien das PDF und die HTML-Dokumente erzeugen.  
Die bisher verwendeten internen Link auf andere Handbuchseiten funktionieren im PDF nicht.  
Für die HTML-Dokumente muss nur ".md" durch ".html" ersetzt werden, was kein Problem ist.

## Die Lösung

Genial einfach.
Die richtige Schreibweise der Link und der Überschriften, sowie im Script "md2pdf" ein sed-Befehl, der den Dateinamen entfernt. 

### Richtige Schreibweise des Link

Nach dem Dateinamen folgt immer die Raute "#" und die Zielüberschrift (Sprungadresse).  
Die Schreibweise bezieht sich auf die Überschrift "### Copyright Rechts- und Lizenzhinweise" im .md-Dokument.
Es gilt vollständige Kleinschreibung und Leerzeichen sind durch "-" zu ersetzen.

~~~
[Siehe Copyright](0000-welcome_de.md#copyright-rechts--und-lizenzhinweise)
~~~

Das Script "md2pdf" entfernt daraus den Dateinamen "0000-welcome_de.md" und erzeugt so einen intern wirksamen Link für das PDF, der so aussieht:

~~~
[Siehe Copyright](#copyright-rechts--und-lizenzhinweise)
~~~

###  Richtige Überschriften

**Keine Sonderzeichen in den Überschriften**  
Erlaubt sind alle wortbildenden Zeichen wie:  
Buchstaben groß und klein, Ziffern und der Unterstrich.  
Das entspricht der Klasse **[:word:]**

Erlaubt sind auch:  
Das **Leerzeichen**, der **Punkt** und der **Bindestrich** bzw. das Minuszeichen.

**Nicht erlaubte Zeichen**  
Diese, und noch viele weitere Zeichen sind in den Überschriften nicht erlaubt:

~~~
, ; : ! ? ^ " ´ ` ' „ “ § $ % & / \  
( ) { } [ ] + * ~ # | < > » «  
&#8482 &gth;
~~~

**Überschriften einzigartig, prägnant und kurz**  
Überschriften, auf die eventuell verlinkt wird, müssen einzigartig sein. Dazu erstelle ich zeitnah eine Liste mit den bisher verwendeten Überschriften.  
Überschriften sollen kurz sein. Das obige Beispiel ist grenzwertig, noch länger ein Unding.  
Besser wäre im obigen Beispiel: "Copyright und Rechte" oder "Lizenz und Rechte"

**Sparsam mit Überschriften umgehen**  
Wie schon im #10 erwähnt, bitte Überschriften sparsam einsetzen. Die guten Auswirkungen der Sparsamkeit habe ich auch erst mit dem ersten, großen PDF gesehen und daraufhin etliche von mir gesetzte umgewandelt.  
Eine Überschrift, dann ein Absatz mit zwei oder drei Zeilen und wieder eine Überschrift ist Unsinn.

### Zur Zeit in Arbeit

+ ~~Die Erweiterung des Script "md2pdf"~~ Erledigt  
+ ~~Erstellung der Überschriftenlisten sortiert nach Dateinamen und nach Überschriftentext.~~ Erledigt 
+ ~~Script für HTML Dateien erstellen.~~ Erledigt  
+ ~~Sonderzeichen aus Überschriften entfernen. (Vorerst nur RC3)~~ Erledigt

Ich hoffe damit in dieser Woche fertig zu werden.

**Comment by hhl** [comment]
Good catch, super!

Manchmal liegt das Gute so nahe, sodass man den Wald vor lauter Bäumen nicht sieht!

**Comment by ak-li** [comment]
Änderung der Überschriften und Link vorerst abgeschlossen.
Wer Lust hat, darf sich gerne auf die Datein stürzen.

**Comment by ak-li** [comment]
Neues siduction-manual.pdf erstellt und vorher div. fehlerhafte Link berichtigt. Einige Link funktionieren noch nicht, da sie auf Handbuchseiten verweisen, die nicht fertig sind.
https://github.com/siduction/sidu-manual/blob/WIP/development/siduction-manual_de.pdf

**Comment by hhl** [comment]
Sieht schon ziemlich gut aus, bis auf ein paar Kleinigkeiten, die sind aber lösbar via Screenshot oder richtigem Zeilensatz (Formatierung).
Andere Sache und dies sollte wohl besser ein extra 'Issue' werden, und auch erst, wenn wir das _de-manual fertig haben, Mehrsprachigkeit! 
Wir können ja nicht nur eine Sprache ausliefern oder getrennt, es müsste ein Dokument sein, manual_en/_de/_fr/_usw mit einer Willkommensseite, welche Sprachvariante wünschen Sie!
Das sollten wir uns mal im Hinterkopf halten!

**Comment by vinzv** [comment]
> Neues siduction-manual.pdf erstellt und vorher div. fehlerhafte Link berichtigt. Einige Link funktionieren noch nicht, da sie auf Handbuchseiten verweisen, die nicht fertig sind.
> https://github.com/siduction/sidu-manual/blob/WIP/development/siduction-manual_de.pdf

Mal zwischendrin ein großes Lob: das sieht schon echt super aus! Vielen Dank für den Einsatz und die Mühe! 👍

**Comment by ak-li** [comment]
Hallo Leute, folgende Dinge sind erledigt:

+ Nummerierung vieler .md-Dateien um eine Hirarchie für das PDF zu erzeugen.

+ Die Erweiterung des Script "md2pdf".

+ Script für HTML Dateien erstellen.  
  Das sind zwei geworden "md2html5.sh", das ruft intern "md2html_pre.pl" auf.

+ Sonderzeichen aus Überschriften entfernen. Überschriften teilweise ändern.

+ In der Folge alle Handbuch internen Link anpassen. (Puhhh, stöhn)

+ In .md-Dateien \<warning\>-Tag in Quote "> " ändern. Erklärung folgt.

Was ich noch nicht geschafft habe:

+ Erstellung der Überschriftenlisten sortiert nach Dateinamen und nach Überschriftentext aus den nummerierten Dateien.  
  Das ist meiner Meinung nach wichtig, damit wir Autoren ein einfaches Werkzeug haben  
  um korrekte Handbuch interne Link zu schreiben.  
  Ist aber in Arbeit.

**Comment by ak-li** [comment]
Die Überschriftenlisten und das zugehörige Script stehen im Ordner /development zur Verfügung.

**Comment by ak-li** [comment]
Habe die Überschriftenlisten und das zugehörige Script aufpoliert, sodass am Zeilenende die vorgefertigten Link für C&P bereitstehen.
Damit wird das Issue geschlossen.
