### ISSUE TITLE
menue-Datei für .html

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#12]
### tree-menue.html

Habe nach dem Vorbild der alten Webseite die Datei "**tree-menue.html**" erstellt.  Das tree-menue enthält keinen Zifferncode in den Dateinamen und Link.  
Das Ganze geschieht mit dem Script "**/development/menue-extract.pl**" aus dem Ordner /data/de/ heraus.  
Die "tree-menue.html" befindet sich wie alle anderen .html-Dateien im Ordner **/data/de/html/**.

Ein Teil der alten HTML-Tag's erscheinen mir recht seltsam. Wir werden später sehen, was passt. Die Änderung im Script ist dann nicht mehr aufwändig.

### HTML-Dateien
Aus den .md-Dateien mit Zifferncode erzeugte ich aktualisierte **.html-Dateien ohne Zifferncode** im Namen und in den enthaltenen Handbuch internen Link; passed zum tree-menue.  
Die verlinkten Bilder in den .html-Dateien werden nur aus dem Ordner "/data/de/" heraus angezeigt. Ich wollte in GIT aber weder die .html-Dateien im Ordner /data/de/ haben, noch den "images/"-Ordner kopieren.

**Comment by hhl** [comment]
@ak-li, für mich sieht die menue-Datei gut aus, wirklich sehr gute Arbeit, einzig vielleicht sollte die Netzwerkeinrichtung, also meist WLAN da LAN meist OOTB funktioniert, prominenter weiter oben im Menue auftauchen da geneigter Nutzer damit oft Startschwierigkeiten vor bzw. nach der Installation hat.

**Comment by ak-li** [comment]
@hhl , die *tree-menue.html* wird mittels Script generiert und soll auf der Webseite ein Aufklappmenü sein, dann ist es nicht mehr so unübersichtlich lang. Ich füge mal etwas css-Code für die Aufklappfunktion in die *tree-menue.html* ein, zur Veranschaulichung.

Deiner Idee entsprechend der Vorschlag:
**Netzwerk:**
- Generell vor Systemadministration einsortieren. Dazu sind die Dateinamen anzupassen.  
- Quickstart in *Konfiguration von Netzwerken* anpassen,  
  - Hinweis LAN meist OOTB,  
  - IWD einfügen und mit kurzen Hinweisen auf Abschnitt Netzwerk,  
  - eventuell als Überschrift 2. Ordnung (##), erscheint dann im Nemü gleichwertig mit Quickstart.

**Comment by ak-li** [comment]
@hhl , Nachtrag Link zur Datei:  
https://github.com/siduction/sidu-manual/blob/WIP/data/de/html/tree-menue.html

**Comment by hhl** [comment]
@ak-li kann so gemacht werden! Danke super!

**Comment by ak-li** [comment]
Datei:  
https://github.com/siduction/sidu-manual/blob/WIP/data/de/html/tree-menue.html  
mit css-Code für die Aufklappfunktion versehen.  
Bitte herunterladen und im Browser testen.

**Comment by ak-li** [comment]
0100-wel-quickstart_de.md angepasst.  
Die alte 'menu_de.md' ist jetzt obsolet und wird von mir, sofern kein Widerspruch erfolgt, in wenigen Tagen entfernt und dann auch das Issue geschlossen.

Als Ergebnis haben wir jetzt eine aus den .md-Dateien mittels Script automatisierte Erstellung des PDF-Handbuches und der HTML-Handbuchseiten.

**Comment by ak-li** [comment]
*menu_de.md* und *wm-dm_de.md* entfernt und Issue geschlossen.
