### ISSUE TITLE
.md5 becomes .html5 

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#16]
@ak-li 
https://github.com/siduction/sidu-manual/blob/WIP/development/md2html_pre.pl
Maybe row 92 causes the issue!

When generating the html files .md5 will be changed in .html5.

See  https://github.com/siduction/sidu-manual/blob/WIP/data/de/0206-cd-dl-burning_de.md and https://github.com/siduction/sidu-manual/blob/WIP/data/de/html/cd-dl-burning_de.html

**Comment by ak-li** [comment]
Fehlerkorrektur mit Commit
https://github.com/siduction/sidu-manual/commit/f922fd57623fd917ddf4dbcdf3d9536549741c17
und
https://github.com/siduction/sidu-manual/commit/e2bd9cf854e5aa40a81e2bf66d4f0c5b78a403b8

@vinzv 
Bitte das Issue schließen, wenn die Dateien auf dem Server sind.

**Comment by ak-li** [comment]
closed with issue #19
