### ISSUE TITLE
0513-ssh_de.md, fehlerhafter Link

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#17]
Unter der Überschrift: **Entfernter Zugriff von einem Windows-PC**
Link "Cygwin XLiveCD" ist nicht erreichbar.
Software ist nur für 32bit Windows, somit veraltet.

Eventuell etwas Neues, oder entfernen?

**Comment by fethomm** [comment]
Alternativen wären meines Erachtens xrdp, VNC oder direkt SSH via Putty.
