### ISSUE TITLE
Rechtschreibung, Kommentar aus dem Forum

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#18]
https://forum.siduction.org/index.php?PHPSESSID=4407ece5603fdb815dc067fab4cf619f&topic=8356.msg67280#msg67280

---------------------------------------------------- snipp -----------------------------------

Hier nochmal der Versuch mit Angabe der Kapitel.
    • Generell sollten alle „Deppenapostrophen“ entfernt werden. Diese sollten mittels Suchen & Ersetzen gefunden und ersetzt werden können. Daher hier nur die ersten Beispiele, die mir ins Auge stachen.
    • 1.0.1 Allgemeines: „im PDF-Format, dass auf allen ISO’s und nach der Installation“
ISO’s --> ISO
    • 3 ISO s: Überschrift in ISOs ändern; ISO’s in ISOs ändern
    • 3.1.2 Varianten der ISO: Titel in „Varianten der ISOs“ ändern
Im letzten Absatz ISO’s in ISOs ändern
    • Anmerkung: Gerade in Überschriften oder einführenden Texten könnte man auch von ISO-Abbildern, ISO-Dateien oder Datenträgerabbildern sprechen. Im weiteren Text würde ich auch die Kurzform ISO bzw. Plural ISOs verwenden.
    • 4.7.3 fstab anpassen: UUID’s in UUIDs ändern (2x)
    • 4.10 LVM-Partitionierung - Logical Volume Manager: SSD’s in SSDs ändern (2x).
    • 5.2.1 IWD installieren: Im roten Feld:
       - Debian sollte als Eigenname einheitlich groß geschrieben werden.
       - „nicht möglich den NetworkManager“ --> „möglich, den“
       - „machen wir darauf Aufmerksam“ --> „aufmerksam“
    • a) 10.0.1 Allgemeines: a) dass --> das
    • 6.1.4 3D Treiber: „Generell ist anzumerken, das fast alle Grafikkarten“ das --> dass
    • dto: „Repository, das diese Firmware nict DFSG konform ist.“ nict --> nicht
Der Satz ist aber insgesamt etwas konfus und gehört neu formuliert.
    • 7 Systemadministration: „Überwachung von Documen-tRoot des Apache Webservers” an unglücklicher Stelle getrennt, DocumentRoot sollte nicht getrennt werden.
    • 7.1.2 Farbiges Terminal: „Farbe des Prompt ändern“ steht (zumindest in meinem PDF) allein in der letzten Zeile und gehört auf die neue Seiten (sogenannter Schusterjunge).
    • 7.3.7 Aktualisierung des Systems: „drei Monate nicht zugewartet werden sollte.“
Hier war sicher gewartet gemeint.
    • 7.3.9 full-upgrade ausführen: Im roten Feld: „kann zu Probleme führen“ --> „Problemen“
    • dto: „Zu beachten ist der folgende Ablauf:“ steht (in meinem PDF) am Ende der Seite. Schusterjunge -> An den Anfang der nächsten Seite setzen.
    • 7.5.2 Module: „ist sicher zu stellen, dass „ --> „sicherzustellen“
    • 7.6 Systemd der System- und Dienste-Manager: „7.6 Systemd der System- und Dienste-Manager
Mein Vorschlag: Entweder „7.6 Systemd, der System- und Dienste-Manager“ oder „7.6 Der System- und Dienste-Manager Systemd“
    • 7.6.2 Unit Typen: „7.6.2 Unit Typen“ wie im Text in „Unit-Typen“ ändern.

---------------------------------------------snapp--------------------------------------------------------------------------

Schusterjungen Regelung ist hoffentlich geklärt und implementiert!

**Comment by fethomm** [comment]
Mach ich morgen

**Comment by ak-li** [comment]
**Achtung bei den Überschriften**
Der Text der Überschrift muss mit einem Buchstaben beginnen, zusätzlich sind nur diese Sonderzeichen erlaubt: **Leerzeichen**, der **Punkt** und der **Bindestrich** bzw. das Minuszeichen.

Alles Andere führt zu kaputten Link entweder im PDF, oder in den .html-Dateien.  
Im Zweifel meckert lieber jemand über die Rechtschreibung, als dass wir uns kaputte Link einbauen.

**Comment by hhl** [comment]
In diesem Falle müssten die Überschriften entsprechend angepasst bzw. geändert werden.

@ak-li 
Kannst Du ein Beispiel dazu nennen?

Eigentlich sehe ich da kein Problem auf uns zukommen, es geht ja um die Apostrophe und deren Einsatz ;).
Und die Überschrift **ISOs** sollte dann doch vielleicht in **ISO-Abbilder** umbenannt werden.

 Da muss ich dem Revision-Leser recht geben, die Häufigkeit der Wörter ISO und ISOs ist schon etwas Inflationär.

**Comment by ak-li** [comment]
Wo nötig, die Überschriften zu ändern, ist ja Sinn dieses Issue.  
Meine Intention war es, noch einmal ausdrücklich darauf hinzuweisen, was bei Überschriften zu beachten ist. Das gilt für alle, die an den .md-Dateien arbeiten, mich eingeschlossen.

**Wiki > DE_Home > Überschriften**  
und  
**Wiki > DE_Home > Link zu Überschriften**  
und  
die Dateien **headline-by-file** und **headline-by-text**

Letzte Woche habe ich einen ganzen Tag damit verbracht fehlerhafte Link in den .html-Dateien durch Korrekturen in den .md-Dateien auszumerzen. Da waren natürlich auch Altlasten von mir dabei. Meine Annahme, dass nach der gleichen Prozedur für das PDF auch die .html-Dateien i. O. sein müssten, war leider falsch.

@hhl
falsch: ### Liste der Quellen (sources.list)

falsch: ### "sources.list" - Liste der Quellen

falsch: ### sources.list - Liste der Quellen  
falsch? -> Die Leerzeichen am Ende sind richtig gemein, denn daraus wird: \<dateimane\>#sources.list---liste-der-quellen-- und sie werden online noch nicht einmal dargestellt.

richtig: ### sources.list - Liste der Quellen

**Comment by hhl** [comment]
Erledigt, thx fethomm (devil)
