### ISSUE TITLE
please rebuild the manual

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#21]
See #16 #17 #18 #19

Fixed spelling and paragraphs, thx edlin
Fixed settings and minor issues, thx akli

**Comment by hhl** [comment]
@ak-li did you generate a new PDF?

**Comment by ak-li** [comment]
Mit 

https://github.com/siduction/sidu-manual/commit/c1f7f75275e5b67fac0884e22c120fd0c5ba3b47

erledigt.
