### ISSUE TITLE
No Getty on tty1 -->  tty2 ist das neue tty1

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#28]
In einigen Artikeln wird noch tty1 beschrieben, um via getty (Konsole) administrative Dinge zu erledigen oder eine Systemrettung einzuleiten.
Dies müsste auf tty2 geändert werden, da dies seit geraumer Zeit wohl der neue Standard ist und so einfach nicht zu ändern ist.
Auch sollten wir das in unseren isos nicht ändern, da dann doch zu viel hinten dran hängt.

We need to replace tty1 with tty2, because of technical changes by systemd

http://0pointer.de/blog/projects/serial-console.html
https://github.com/systemd/systemd/issues/12345
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966414
https://www.mail-archive.com/debian-qt-kde@lists.debian.org/msg84775.html
usw.

In unserem Forum ist auch einiges dazu zu finden.

**Comment by davydych** [comment]
Danke für den Hinweis.
Ist das für zukünftige Versionen des Handbuchs relevant? In der aktuellen finde ich nämlich nichts zu getty. tty1 wird lediglich am Ende von Abschnitt 1.2.6 _siduction IRC-Support im Textmodus_ erwähnt.

**Comment by hhl** [comment]
Mh, es ist schon relevant auch für zukünftiges, vielleicht kommt ja noch das ein oder andere dazu.
Wenn es jetzt nur in einem Kapitel vorkommt, ist dies ja gut und hält den Aufwand gering.
Man muss aber auch nach jenem Ausschau halten -> 'Alt + Strg + F1'  oder 'Alt+Ctrl+F1.
Da müsste das F1 in F2 geändert werden, ansonsten landet man an falscher Stelle und sieht nur die Bootmeldungen bzw. einen schwarzen Bildschirm.

**Comment by davydych** [comment]
Gut, dann werde diese Stelle heute Nachmittag in der deutschen und der englischen Version ausbessern und in Zukunft auch darauf achten.

**Comment by ak-li** [comment]
Zur Unterstützung hier die einzigsten Fundstellen (auch mit anderen Suchmustervarianten probiert):
in DE mit: 
/data/de$ grep -on -e 'Alt.*F1' *
0202-live-mode_de.md:57:Alt` + `Strg` + `F1 (Zeile 57)

in EN mit:
/data/en$ grep -on -e 'Alt.*F1' *
0202-live-mode_en.md:52:Alt`+`Ctrl`+`F1 (Zeile 52)

Das gesamte Verfahren zu der Anmeldung von TTY1 weg zu TTY2 ist anzupassen, da ja noch kein Login vorhanden ist, wie gestern im IRC von mir beschrieben:
Am Promt "siduction login:" siducer eingeben und ENTER und PW "live" und ENTER, dann "su" und ENTER geht.
Nur "su" und ENTER  reicht nicht mehr.

@davydych 
Bitte auch in Zeile 62 der 0202-live-mode_en.md "Ctrl" wieder entfernen. Das ist nicht wirklich falsch, aber nicht nötig.
Um zwischen den TTY 1-6 zu wechseln reicht "Alt+Fx", um zur GUI zurück zu kehren "Alt+F7".

**Comment by ak-li** [comment]
Mit dem geänderten Verhalten von TTY1 ist die Zeile 57 in 0202-live-mode_de bzw. Zeile 52 in 0202-live-mode_en Nonsens!
Erklärung:
"Wenn ich mich ausgesperrt habe..." bedeutet, dass ich das Passwort für siducer geändert habe und es nicht mehr weiß.
Dann hilft auch kein TTY2, da ich mich dort, bevor ich zu root werden kann, als siducer mit Passwort anmelden muss. Der Wechsel mit Strg+Alt+F2 zu TTY2 ist Quatsch und hilft dem Benutzer für diesen Fall in keiner Weise weiter. Die einzige Lösung besteht in einem reboot.

Die Überschrift lautet: ### Ein neues Passwort setzen
Daran sollten wir uns halten.
Lösungsvorschlag mit folgendem Text:
Zeile 57: Noch einmal zur Erinnerung. Der Standardbenutzer in der Livesession ist **siducer** mit dem Passwort **live**. Will man das Passwort ändern, so öffnet man ein Terminal und gibt die folgenden Befehle ein.
Lösungsvorschlag Ende.
Die Zeile 68 ist zu entfernen.

Mit der Bitte um Rückmeldung.
Gruß akli

**Comment by hhl** [comment]
Da muss ich Dir recht geben, es ist wirklich Nonsens.
Von meiner Seite aus finde ich den Vorschlag gut, ich würde es so oder ähnlich machen.

**Comment by fethomm** [comment]
ACK

**Comment by davydych** [comment]
Würde das dann direkt umsetzen wie von @ak-li vorgeschlagen.

**Comment by fethomm** [comment]
Do it to it.

**Comment by ak-li** [comment]
Fixed with commit 3882d0 and b275b9b.

@davydych
Vielen Dank, dass du dich der englischen Seiten angenommen hast. Ich finds einfach toll.
