### ISSUE TITLE
IWD neue/new main.conf

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#29]
IWD 1.21-2 provides now its own /etc/iwd/main.conf.
IWD 1.21-2 wird mit eigener /etc/iwd/main.conf ausgeliefert.

If someone installs or update  IWD (>=1.21-2)  he/she only had to modify the main.conf,
In our case, by removing the comment (#) at the line  ''#EnableNetworkConfiguration=true"
That is the only thing he/she had to do as long as systemd is used, in other cases they have to change a bit more, all is described in the main conf, or the man page.

An easy way to do so:

sed -i 's/#EnableNetworkConfiguration=true/EnableNetworkConfiguration=true/' /etc/idw/main.conf

All other steps don't change!

For iwd installation <=1.21-2 the old procedure is the right one

**Comment by ak-li** [comment]
Fixed with commit a385fc6
https://github.com/siduction/sidu-manual/commit/a385fc60960c1995e0ab56ba586a7fe3d552b264
