### ISSUE TITLE
branch "WIP"

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#3]
Möchte der Übersicht halber von den md-Dateien mit Status RC1 die ursprünglichen htm-Dateien entfernen.
Lege zu diesem Zweck einen Branch mit dem Namen WIP an.
Wir sollten dann nur noch auf dem Branch arbeiten und Master in Ruhe lassen.

**Comment by hhl** [comment]
Ich habe die WIP branch als default branch markiert statt master, diese wird nun als master-branch die nächste Zeit behandelt.

**Comment by hhl** [comment]
@ak-li gibt es schon htm(l) dateien, die man entsorgen könnte?

**Comment by ak-li** [comment]
@hhl 
Die htm-Handbuchseiten, deren md-Datei bereits (weitgehend) aktualisiert wurde, habe ich schon entfernt. Auch erkennbar an der Statuszeile "Status: RC1" im Header der md-Datei.
Bei Dateien mit "WIP" im Namen wurde die Aktualisierung begonnen.
Handbuchseiten mit gleichem basename und dem Vohandensein beider Erweiterungen (.htm und .md) sind noch unbearbeitet.

**Comment by hhl** [comment]
akli, Geduld bitte, ich werde schauen und hoffe auch andere, und nicht aufgeben, es wird ein wenig dauern, und ja von der fachlichen Seite bin ich auch nicht die erste Wahl und ich mache mir auch meine Gedanken dazu, aber ich werde mich, so weit ich kann kümmern. Bitte habe Geduld!
