### ISSUE TITLE
They demoted wpasupplicant to recommends in network-manager

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#30]
Read the changlog
```
network-manager (1.34.0-2) unstable; urgency=medium

  * Demote wpasupplicant to Recommends.
    There are enough use cases for network-manager not involving Wi-Fi which
    justifies to make this dependency optional. (Closes: #919619, #980218)

 -- Michael Biebl <biebl@debian.org>  Tue, 18 Jan 2022 20:59:36 +0100
```
So with network-manager >= 1.34.0-2 it is possible not to install or remove wpasupplicant.
We have to rethink the workflow of how IWD will be installed and enabled.
I refer [0502-inet-iwd_de.md](https://github.com/siduction/sidu-manual/blob/WIP/data/de/0502-inet-iwd_de.md) and  to [0502-inet-iwd_en.md](https://github.com/siduction/sidu-manual/blob/WIP/data/en/0502-inet-iwd_en.md)

**Comment by vinzv** [comment]
From what I read in the manual, there's nothing necessary to change there. Steps to disable wpasupplicant and enable iwd are already there.

For the ISO configs:
While it's not very clean and pretty, we could as well just disable wpasupplicant and leave the package installed.

**Comment by fethomm** [comment]
We should leave it installed, in case someone wants to go back to it from iwd.

**Comment by ak-li** [comment]
iwd is installed and activated by default and wpa_supplicant.service is masked.
Change in the manual was made with https://github.com/siduction/sidu-manual/commit/2bcbf84f2cd69aee80b077c693fb9b5623f4f95b .
No further action is necessary.
