### ISSUE TITLE
In some pages, we refer to init 3 and init 5, but we use systemd

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#31]
In the chapter/page https://github.com/siduction/sidu-manual/blob/WIP/data/de/0100-wel-quickstart_de.md and _en.md we use "init 3" and "init 5", maybe in some other chapters too.
In siduction we use systemd, so the new "init" 3 is the  multi-user.target, to reach it, it can be done by following commands "systemctl isolate multi-user.target" or "systemctl stop sddm.service" (if sddm is used as display manager).
Init 5 is now called "grapical.target", you can reach it with "systemctl isolate graphical.target" or "systemctl start sddm.service".
All done in (getty) ctrl+F2(-F6) tty2 -tty6 as root.

**Comment by ak-li** [comment]
Das ist bekannt und meiner Meinung nach auch abschließend geregelt, denn selbst in der manpage systemd steht ein entsprechender Hinweis.

Bei uns steht es in "0702-sys-admin-gen"
> Die alten sysvinit-Befehle werden weiterhin unterstützt. (hierzu ein Zitat aus man systemd: "... wird aus Kompatibilitätsgründen und da es leichter zu tippen ist, bereitgestellt.")

**Comment by hhl** [comment]
Dann ist gut.
Sollte es denn eine kurze Erwähnung auf der Schnellstartseite finden, als Hinweis?
Frei nach dem Motto: Auch wenn siduction systemd nutzt, werden hier die alten sysvinit-Befehle verwendet, da diese … usw. Siehe …
Ist jetzt nur eine Frage, muss nicht!

**Comment by ak-li** [comment]
Ich möchte das nicht abwiegeln, aber so ganz erschließt sich mir nicht der Sinn eines zusätzlichen Hinweises.
Du beziehst dich auf die Seite "0100-wel-quickstart" ?

Der init-Befehl taucht dort ausschließlich im Kapitel
**Aktualisierung des Systems - upgrade**
zweimal auf. Erst `init 3` und dann `init 5`.
An dieser Stelle würde der Hinweis nach meiner Meinung nur verwirren.

Folgend alle Textstellen mit "init ".

In "0003-help" unter der Überschrift **Nützliche Helfer im Textmodus** steht es z.B. so:
`Normalerweise verwendet man den Textmodus Runlevel 3 (init 3 bzw. journalctl isolate multi-user.target)...`
In "0520-lamp-start" Zeile 40 steht:
`Wie bei siduction üblich, erledigen wir die Installationen im "multi-user.target" (init 3) im Terminal.`

In den Dateien "0711-systemd-unit-datei" wird der init-Befehl mit der systemd Entsprechung genannt und in "0714-systemd-target" der Zusammenhang beider ausführlich erklärt.

Handlungsbedarf besteht eventuell in der Datei "0705-sys-admin-apt" Zeilen 125 und 378. Hier wäre der Text
`In den Textmodus gehen mit Ctrl+Alt+F2`
anzupassen. Etwa so:
`Mit Ctrl+Alt+F2 auf die Textkonsole wechseln`

Eure Meinung?

**Comment by hhl** [comment]
Mir war dies beim Überfliegen der Seite halt aufgefallen, habe da jetzt auch nicht weiter geforscht. Da siehst du, wie tief ich im Handbuch stecke. Das brauchst du nicht abbügeln, wie gesagt, ist mir  ins Auge gefallen und ich habe regiert. Also kannst das Issue schließen.
Und ja, es liest sich flüssiger,

**Comment by ak-li** [comment]
Mit Änderungen der beiden "0705-sys-admin-apt" (https://github.com/siduction/sidu-manual/commit/8266205648a09564424ccfa2a032d1d5142b9f37) geschlossen.

@hhl
Das Issue hat doch zu Verbesserungen geführt. :-)
