### ISSUE TITLE
Generation of the manual files (PDF and HTML) with one program call.

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#32]
Auf Anregung von vinzv möchte ich im Ordner "/development" ein Script erstellen, dass mit Hilfe mehrere schon bestehender Scripte alle notwendigen Dateien für die Veröffentlichung des Handbuches in allen zur Verfügung stehenden Sprachen generiert.

**Comment by ak-li** [comment]
Mit commit https://github.com/siduction/sidu-manual/commit/d250c17e209b03955b0f2900db7a29d8b497519c erledigt.

Das Script `00-generate-manual.pl` im Ordner `/development` erstellt mit Hilfe der anderen numerierten Dateien das PDF, die einzelnen HTML-Dateien und die HTML-Menue-Datei in den gewünschten und zur Verfügung stehenden Sprachen. Der Aufruf lautet
`./00-generate-manual.pl en de` im Ordner `/development`
für alle Handbuchdateien in den Sprachen Englisch und Deutsch.

Es ist auch möglich nur einen Teil neu zu erstellen. Beispiele:
`./10-generate-pdf-manual.sh .en` erstellt das PDF-Handbuch in Englisch,
`./20-generate-html-manual.sh de` erstellt die HTML-Handbuchseiten in Deutsch,
`./30-generate-html-menu.pl de` erstellt das HTML-Menü in Deutsch.

**Comment by fethomm** [comment]
Gute Sache, danke!

**Comment by ak-li** [comment]
### pandoc zu HTML produziert Fehler mit Umlauten

Bereits in den .md-Dateien umkodierte Umlaute (`ü` -> `&uuml;`) schreibt pandoc bei der Erstellung der HTML Dokumente wieder zurück.
Aus diesem Grund habe ich die Scripte mit commit https://github.com/siduction/sidu-manual/commit/ba28dd93c90b400de47ce83a11f2f490c319cfff entsprechend angepasst.
Gleichzeitig wurden die Header entsprechend den zur Zeit online befindlichen HTML-Seiten angepasst.

@vinzv 
commit https://github.com/siduction/sidu-manual/commit/d5c53f63e0695e052209f5cec5e164985b86e8cb
Kannst du bitte die neuen HTML-Seiten testen.
Bei der Menüdatei habe ich die Einrückungen stark reduziert, damit der Text in dem schmalen Frame besser zu lesen ist.

**Comment by ak-li** [comment]
Arbeit erledigt, commit https://github.com/siduction/sidu-manual/commit/e242a584bd7cfce7775fedd0f04639a562fc5805, https://github.com/siduction/sidu-manual/commit/8d22e440d934c451a73f94f284156d5444eb8ffa und https://github.com/siduction/sidu-manual/commit/cc57a464a9a6dd8b254cb363530d51983103c597 mit einem Programmaufruf von `00-generate-manual.pl` erstellt.
