### ISSUE TITLE
Bring multilingualism of the manual to the live media and the website.

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#33]
For the next release we should achieve this.

**Comment by ak-li** [comment]
Die Übersetzung ins englische ist weitgehend erledigt. Das Layout für das PDF geht der Vollendung entgegen. 
Es fehlt noch:

+ ~~Prüfung des Layout für die HTML Dateien~~
  Erledigt. CSS an die geänderte Schriftgröße des Codes angepasst.
+ ~~Farben in den HTML Dateien bezüglich issue 49~~  
  Alles schwarz, grau, weiß. Nur besuchte Link sind orange und der Hintergrund der Tabellen hat eine von grau etwas abweichende Farbe.
+ Responsive Design für die Webseite des Handbuches
+ ~~Abschließender Test der automatischen Erstellung der gesamten Handbuchdateien (issue 32)~~
  Erledigt.

@vinzv 
Kann ich dir bei der Webseite irgendwie helfen? Z.B. mit css-Datei.

**Comment by vinzv** [comment]
Der neueste Snapshot vom 01.05.22 ist jetzt online. Es gibt eine Vorschaltseite für DE/EN

Zum responsiven Design:
Die Seite ist (noch) ein Frameset, sprich nur sehr bedingt responsive, weil das Manual im Grunde aus zwei Dateien besteht:
1. tree-menue
2. der jeweilige Inhalt.

Ich kann jetzt schon anfangen, alles nachträglich händisch zu mergen. Sinnvoller erscheint mir aber, das direkt mit pandoc zu machen. Allerdings weiß ich hier nicht wie das geht.

**Comment by hhl** [comment]
@vinzv, Danke, nur eine Sache, der EN-Link verweist noch auf DE.

@ak-li, @Mister00X, @davydych besonderer Dank an Euch!

**Comment by hhl** [comment]
Gut, gefixt, EN verweist auf EN

**Comment by ak-li** [comment]
@vinzv 

> Ich kann jetzt schon anfangen, alles nachträglich händisch zu mergen. Sinnvoller erscheint mir aber, das direkt mit pandoc zu machen. Allerdings weiß ich hier nicht wie das geht.

Sag mir was du benötigst. Ich bau das ein.
Oder erstelle mir eine Musterseite.

**Comment by vinzv** [comment]
Ich habs mal in ein extra Issue gepackt: https://github.com/siduction/sidu-manual/issues/56

**Comment by ak-li** [comment]
> Ich habs mal in ein extra Issue gepackt: #56

Damit ist dieses Issue erledigt. Dank an alle, die daran mitgearbeitet haben.
Ich schließe es.
