### ISSUE TITLE
EN translation

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#34]
@davydych, kannst du bitte Ausdruck und Rechtschreibung überprüfen. Danke.
Geringfügige Änderung in
0301-hd-install_en.md Zeile 158

**Comment by ak-li** [comment]
@davydych, kannst du bitte Ausdruck und Rechtschreibung überprüfen.  
https://github.com/siduction/sidu-manual/commit/b36bde084e2412d742146dc47df621610df09566  
0701-term-konsole_en.md, Zeilen 230-234

Vielen Dank

**Comment by ak-li** [comment]
Noch einmal auch von meiner Seite vielen Dank für deine Arbeit.

Die in deinem Commit https://github.com/siduction/sidu-manual/commit/f0b526b1be9bf9fdd1235f6e07e17ca5817ca928 beschriebenen Dateien 0000-welcome_en und 0200-isos_en sind nun aktuell und harren deiner Fähigkeiten.

Die deutschen 0206 - 0209 Dateien warten auf einen Review und anschließend auf die Übersetzung. Sobald die Arbeiten daran erledigt sind steht der englischen Version des Handbuches nichts mehr im Weg.

**Comment by ak-li** [comment]
@davydych 
I made minor adjustments to the text in two files as part of the formatting process.

0703-sys-admin-doas_de.md
line 61-65 and 80 (logical mistake of the configuration)
line 69 (whole path)

0705-sys-admin-apt_de.md
line 245-252 (expression, sentence structure)
line 383-390 (expression, sentence structure)

**Comment by ak-li** [comment]
@davydych 

Now the files 0206- up to 0209- inside the en-folder are new or updated.
Please have a look at them.
I am proud and happy that we can finish the work.
Thank you for your commitment.

**Comment by davydych** [comment]
@ak-li 

Sure, I'll do the translations, but first I would like to finish the files on systemd.
The English manual should be ready in a couple of days.

**Comment by ak-li** [comment]
@davydych 
I think we can close this issue now. When new files come in we will open a new one. 
Thanks for the lots of good work.

**Comment by ak-li** [comment]
@davydych 
Kannst du mir wieder behilflich sein?
Ich habe in der Datei [EN_Home](https://github.com/siduction/sidu-manual/wiki/EN_Home) unter "7. Code block" Zeile 110 bis 115 deutschen Text eingefügt, der zu übersetzen wäre.

Vielen Dank

**Comment by davydych** [comment]
@ak-li 
Erledigt

**Comment by ak-li** [comment]
Danke
