### ISSUE TITLE
su vs. su -

### ISSUE THREAD

**Issue by fethomm** [siduction/sidu-manual#36]
I suggest substituting 'su' with 'su -', since 'su' does not grant a full root anymore.

**Comment by ak-li** [comment]
I think nothing to do.

Ich hatte in den letzten Jahren noch nie Probleme  mit dem Kommando su.
Die Verlagerung des Kommandos 'su' von shadow zu util-linux wurde in Buster (2019-07-06) eingeführt und war somit schon vorher in sid.
Die Recherche von **Debian Bug report logs - #833256** und **https://wiki.debian.org/NewInBuster** ergab u.A. folgende Abhilfemaßnahmen:

1. Use su - instead; this launches a login shell, which forces PATH to be changed, but also changes everything else including the working directory. 
2. Put "ALWAYS_SET_PATH yes" in /etc/default/su to get an approximation of the old behavior.
3. Put the system administration directories (/sbin, /usr/sbin, /usr/local/sbin) in your regular account's PATH

Nr 1 ist nicht notwendig, da Nr 2 und Nr 3 Verwendung finden.

~~~
cat /etc/default/su
ALWAYS_SET_PATH yes

grep -E '(^ENV_SUPATH|^ENV_PATH)' /etc/login.defs
ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/game
~~~

Ein Nachteil von "su -" besteht darin, dass in das Verzeichnis `/root` gewechselt wird, während bei Verwendung von "su" das aktuell betretene Verzeichnis erhalten bleibt.

Wer in siduction für den workaround verantwortlich ist, weiß ich nicht. Aber er hat es gut gemacht!
