### ISSUE TITLE
Reordering the 0206 ff - files

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#37]
Im Bereich Download und Brennen gibt es strukturelle und inhaltliche Unstimmigkeiten.

- Es fehlen dort Informationen zu USB-Stick/SD-Card
- Download und GUI brennen in einer Datei
- Eine ganze Reihe von Konsolebefehlen, die nicht mit den Isos in Zusammenhang stehen

Mein Vorschlag mit neuen Dateinamen und teilweise neuen Überschriften:

~~~
0200-isos                                           #   ISO-Abbilder (unverändert, hier nur zur Info)
0206-cd-dl-burning      ->  0206-iso-dl             ##  ISO download
0303-hd-ins-opts-oos    ->  0207-iso-to-usb-sd      ##  ISO auf USB-Stick - SD-Card
neu: Teil aus 0206      ->  0208-iso-to-dvd         ##  ISO auf DVD brennen
0207-cd-no-gui-burn     ->  0209-no-gui-burn        ##  DVD ohne GUI brennen
                                                    ### burniso
                                                    ### Verfügbare Geräte
                                                    ### Brennen mit cdrdao und wodim 
                                                    ### Nützliche Beispiele für CD und DVD (hierauf aus 0701-term-konsole verlinken)
~~~

Die bisherigen Verlinkungen auf die Dateien sind nur minimal und stellen keinen großen Änderungsaufwand dar.

**Comment by hhl** [comment]
Von meiner Seite ist dies so OK.
Werden die am Thema vorbeiführenden CD/DVD Brennbefehle  via Konsole (eher Kategorie Tipps und Tricks) nach 0701 verschoben und dann an entsprechender Stelle in 209 mit Hinweis verlinkt ->  0701, verstehe ich das richtig?

**Comment by ak-li** [comment]
> Werden die am Thema vorbeiführenden CD/DVD Brennbefehle via Konsole (eher Kategorie Tipps und Tricks) nach 0701 verschoben und dann an entsprechender Stelle in 209 mit Hinweis verlinkt -> 0701, verstehe ich das richtig?

Ich dachte genau anders herum. weil "Verfügbare Geräte" und "Brennen mit cdrdao und wodim" ja Voraussetzung für "Nützliche Beispiele für CD und DVD" sind. Außerdem hat die 0209 ohne die Beispiele nur 30 Zeilen und Dinge wie ISO-Abbilddatei erstellen passen wiederum in beide Dateien.

**Comment by hhl** [comment]
Wenn dem so ist, du hast freie Hand von meiner Seite aus.

**Comment by ak-li** [comment]
**Überprüfung notwendig**

```
0200-isos_de.md            umfangreich geändert
0206-iso-dl_de.md          geändert, brennen entfernt
0207-iso-to-usb-sd_de.md   neu, teilweise aus gelöschter 0303-hd-ins-opts-oos_de.md
0208-iso-to-dvd_de.md      neu, Teil aus 0206-iso-dl_de.md
0209-no-gui-burn_de.md     umfangreich geändert, war zuvor 0207-cd-no-gui-burn_de.md
0300-install_de.md         Link zu 0303-hd-ins-opts-oos_de.md entfernt
0701-term-konsole_de.md    Zeilen 227 - 233 geändert
```

Zeitnah folgt noch die Änderung der internen Links anderer Seiten.

**Comment by ak-li** [comment]
With https://github.com/siduction/sidu-manual/commit/e428fba93aa9a3005b73e34ec545797a6451f411 finished.
