### ISSUE TITLE
Formatting 0311-part-uuid

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#39]
@davydych 

I run into a formatting issue at line 46-56.
The table with the commands for the labels in different file systems is badly readable and the code `<LABEL>` is not displayed.

+ The angle brackets would have to be masked and the code `<LABEL>` should be written in lower case.
+ The commands are nevertheless poorly readable, as I tested.
+ The format conventions do not translate well visually.

Therefore I have a suggestion:
We use a list.

+ File system bold, according to the format conventions.
+ Command in the next line and highlighted, also according to the format conventions.
+ Thus no masking of the angle brackets necessary.

This is how the result looks:

+ **swap**  
  `swaplabel -L <label> /dev/sdXx`
  
+ **ext2/ext3/ext4**  
  `e2label /dev/sdXx <label>` or `tune2fs -L <label> /dev/sdXx`
  
+ **jfs**  
  `jfs_tune -L <label> /dev/sdXx`
  
+ **xfs**  
  `xfs_admin -L <label> /dev/sdXx`
  
+ **reiserFS**  
  `reiserfstune -l <label> /dev/sdXx`
  
+ **fat**  
  `fatlabel /dev/sdXx <label>`
  
+ **ntfs**  
  `ntfslabel /dev/sdXx <label>`

If you like it (I hope so), you can click on the three dots in the top right of this comment and select "edit". Then copy&paste the list into the english file. Additionally please insert "depending on file system" in line 46.
Please let me know if you take the suggestion.

**Comment by davydych** [comment]
@ak-li 
I agree with you and I will copy the list into the English file right now.
