### ISSUE TITLE
PDF-Manual, Internal link lead to the paragraph BEFORE the destination address

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#40]
Internal link lead to the paragraph before the destination address and thus partly to the previous page.
This is an issue with LaTex and affects the file  
[11-helpfile-pdf-manual-header.tex](https://github.com/siduction/sidu-manual/blob/WIP/development/11-helpfile-pdf-manual-header.tex)

**Comment by Mister00X** [comment]
I think I have found the culprit
https://github.com/siduction/sidu-manual/blob/5fed907071e381bbb299609db1f96bb6c524a9b0/development/11-helpfile-pdf-manual-header.tex#L34-L40

According to the `hyperref` manual (version 2021-06-07):
> 9.1.38 titlesec
> nameref supports titlesec, but hyperref does not (unsolved is the anchor setting, missing with
> unnumbered section, perhaps problems with page breaks with numbered ones).  

Pandoc uses `hyperref` for creating links so I assume there is some mismatch in position because of the use of `titlesec`.  

What was the initial reason for using `titlesec`? Do you really want that every section **and** subsection start on a new page?

I don't have a running pandoc instance here so I can't check the generated LaTeX code but I assume it is using `\documentclass{article}`. Having the first level of headings start on a new page could easily be achieved by switching from article to report because afaIk `\chapter{}` in the report class start always on a new page (they do in the KOMA-Script version of this class:`scrreprt`).  
Otherwise I may need to do some research in finding a `hyperref`-compatible alternative for `titlesec` or *somehow* tell pandoc that it shall issue a `\clearpage` before both `\section{}` and `\subsection{}`

Do you all have somewhere documented what kind of layout you want for the PDF-version?  
Maybe some of the headaches could be avoided/simplified by switching to KOMA-Script and utilizing some of it's features.

Could someone give me a short explanation on how to generate the PDF with the scripts in `development/` e.g. (what do I need to execute in which order to generate one myself)?
I'd like to check if my assumption that `titlesec` is the culprit here is true.

**Comment by ak-li** [comment]
@Mister00X 
First of all, thank you for your answer.

> Do you all have somewhere documented what kind of layout you want for the PDF-version?

Not separately, but as some options in files `10-generate-pdf-manual.sh` and `11-helpfile-pdf-manual-header.tex`.
Due to lack of own expertise we used code snippets found on the Internet that seemed useful.

Additional this wiki page contains the MD code we use.
https://github.com/siduction/sidu-manual/wiki/EN_Home#md-code-for-block-elements
Regarding the headings, in the PDF the first and second order ones (# and ##) should start on a new page.

> Could someone give me a short explanation on how to generate the PDF with the scripts in development/
+ The script `00-generate-manual.pl` calls successively the scripts `10-generate-pdf-manual.sh`, `20-generate-html-manual.sh` and `30-generate-html-menu.pl`.
+ The script `10-generate-pdf-manual.sh` calls the script `11-helpfile-pdf-manual-header.tex`.  
  You can also call it directly to create only the PDF.
  The usage of the scripts is explained in their headers.

**Comment by Mister00X** [comment]
@ak-li Thanks for the explanation.

> Regarding the headings, in the PDF the first and second order ones (# and ##) should start on a new page.

I think the easiest way to fix this is to kick the `titlesec` package and simply redefine the `\section{}` and `\subsection{}` macros to include a `\clearpage` before them **but** this will IMHO create a problem with https://github.com/siduction/sidu-manual/blob/ffc547a9881123f0a09dcfd718f7abe9933ed87b/data/de/0100-wel-quickstart_de.md?plain=1#L3-L5  where there is a level 2 heading immediately after a level 1 heading. The redefinition of those two macros would lead to a nearly empty page only containing the level one heading `Quickstart`. :-/

Unfortunately the build of the PDF with pandoc currently fails for me with an error (supposedly a pdflatex one)
```
$ ./10-generate-pdf-manual.sh de
Error producing PDF.
! Extra }, or forgotten \endgroup.
^^M->\lst@DeInit \egroup
                         \global \let \lst@inlinechars \@empty \PackageError...
l.3173 ...for grub2-fll-fromiso update-grub helper
```
so it seems I can not start experimenting with this. Also pandoc seems to not create any logs or give me access to the LaTeX code it generated for PDF-generation. (I'm going to have a look at pandocs documentation, once I got some spare time. Maybe it has a debug-mode or something the like.)

**Comment by ak-li** [comment]
> Unfortunately the build of the PDF with pandoc currently fails

Same for me. :-1:  Before you look long:
The problem exist in `0302-hd-ins-fromiso_de.md`. I renamed it to `hd-ins-fromiso_de.md`. Now pandoc fit the PDF.
I'll find the mistake in inside the file.

> but this will IMHO create a problem with `0100-wel-quickstart_de.md`

I think the easier way is to change the heading line 5 to bold text, as it is in `0000-welcome_de.md`. Because there are no subgroups. I just tested it. Looks good.
All other 0x00 files are the start of a new main group that contains only links and short explanations to the other pages, similar to a table of contents. This only does not apply to 0600, as other subgroups are still to follow. Then we will adapt the layout there as well. For the time being, we can live with the small flaw.

**Comment by Mister00X** [comment]
> Same for me. -1 Before you look long:
> The problem exist in `0302-hd-ins-fromiso_de.md`. I renamed it to `hd-ins-fromiso_de.md`. Now pandoc fit the PDF.
> I'll find the mistake in inside the file.  

Please give me a short ping when you fixed the error in `0302-hd-ins-fromiso_de.md` so I can pull in the fix before sending a pull request. In the meantime I will also rename it.



> I think the easier way is to change the heading line 5 to bold text, as it is in `0000-welcome_de.md`. Because there are no subgroups. I just tested it. Looks good.
> All other 0x00 files are the start of a new main group that contains only links and short explanations to the other pages, similar to a table of contents. This only does not apply to 0600, as other subgroups are still to follow. Then we will adapt the layout there as well. For the time being, we can live with the small flaw.

Great. In that case I will start experimenting this afternoon/evening. (Hopefully my idea does not also break hyperref :stuck_out_tongue_closed_eyes:)

**Comment by Mister00X** [comment]
~Great news. LaTeX appears to ignore the additional `\clearpage` if there is no text between two headlines. So no changes are needed on the `Quickstart` headline.~ Scratch that, i was wrong.

I am currently still experimenting (aka. clicking the links in the PDF like a maniac) but my idea appears to work.

**Comment by hhl** [comment]
Hi, I found the error and fixed it, see [de6808c](https://github.com/siduction/sidu-manual/commit/de6808c8ba053f0bed08c3415f52456a0564546a)

**Comment by ak-li** [comment]
Commit https://github.com/siduction/sidu-manual/commit/b2502447eb22f18df3ff6db8f1e6604c61ef3067 solves the headline issue of `0100-wel-quickstart_de.md`

Commit https://github.com/siduction/sidu-manual/commit/823f9ad20ed153240b6ced991be14e1b0ceb3d00 solves the issue of generation PDF. Mistake at line 35 in `0302-hd-ins-fromiso_de.md`
The English files contain some similar errors. I am looking for them right now.

**Comment by ak-li** [comment]
Commit https://github.com/siduction/sidu-manual/commit/e31dffd01e7ed44e2a050ab01602c6cf2b58b7ae solves the issue of generation en-PDF

**Comment by ak-li** [comment]
Commit https://github.com/siduction/sidu-manual/commit/df266085c311131509969c8d66f21d509fca9587 solves the headline issue of `0100-wel-quickstart_en.md`

@Mister00X 
Now all errors that hindered the creation of the PDF should be removed. I hope so.

The new PDF (de and en) also updated.

**Comment by Mister00X** [comment]
Okay I'll try a rebase and send an PR afterwards.
