### ISSUE TITLE
In the English manual (PDF?), there is the word Abbildung

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#42]
Under images/pictures there is the word "Abbildung NN, some text". 
At least in the generated PDF document.
Maybe it is generated by a script?

**Comment by hhl** [comment]
I have done a little test.

In the 11-helpfile-pdf-manual-header.tex,
if we change \usepackage[main=ngerman, english]{babel} to \usepackage[main=english]{babel}

Then  the output is the right one, Figure instead of Abbildung.

**Comment by Mister00X** [comment]
I think I already found the culprit.
There is some kind of double definition in `10-generate-pdf-manual.sh` and `11-helpfile-pdf-manual-header.tex`, pandoc allready uses babel but the variable for setting the language has the wrong name. 

I'll send a PR soon.
