### ISSUE TITLE
0303-hd-ins-fromiso_en to be removed?

### ISSUE THREAD

**Issue by davydych** [siduction/sidu-manual#47]
@ak-li 
I was comparing the German and English version of the manual, when I mentioned a difference in Chapter 4.
The English version contains the subsection "4.3 Installation on USB stick - memory card", while the German version does not. 
By comparing the folders, I can see that there is no `0303-hd-ins-fromiso_de.md` in the `de/` folder.

I assume, that the English file `0303-hd-ins-fromiso_en.md` needs to be removed?

**Comment by ak-li** [comment]
@davydych 
You are right.
Deleted with commit https://github.com/siduction/sidu-manual/commit/7b0c09bb393d643f5d8b574bae13673cc58c6fb2
