### ISSUE TITLE
PDF: numbering and subsections on a new page

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#48]
@davydych , @Mister00X  , @hhl 
We had a whole series of shortcomings with the layout of the PDF. It started with issue #40, the improvement led to https://github.com/siduction/sidu-manual/issues/40#issuecomment-1098927781 (each subsection starts on a new page) and the changes I made were not satisfactory and led to commit https://github.com/siduction/sidu-manual/commit/ef49b12dfa0eef676b6fbbacba21854b81c328a0 and https://github.com/siduction/sidu-manual/commit/62137bcc63187c664f2e87c7cbaf1a23b5594bfc.

@davydych , your findings about the numbering in the PDF are absolutely correct. So I thank you for your food for thought. I saw it more from the technical side and neglected the good layout.
Two things collide: the handling of headings by pandoc (LaTex) on the one hand and the handling of headings in the md files on the other hand. I think I have found a good solution.

1. by the structure and numbering of the md files the page break is already given. So my changes in 0000- and 0100- , to prevent the additional page break, harm the layout.
2. pandoc (LaTex) should insert a page break automatically only at "sections" and not at "subsections". "sections" are e.g. the title page, the table of contents and the class 1 headings (#).
3. A page break before class 2 headings (##) may only occur when an md file begins. We achieve this by having the script `10-generate-pdf-manual.sh` append the LaTex code `\clearpage` to each file.

Will be committed shortly.

**Comment by ak-li** [comment]
@Mister00X 
Please check if the double use of "\clearpage" can cause problems. 
Inserted between files 0003- and 0100- , once from `10-generate-pdf-manual.sh` and once from `11-helpfile-pdf-manual-header.tex`.

The PDF looks good at this point.

**Comment by Mister00X** [comment]
Am 18. April 2022 14:58:34 MESZ schrieb ak-li ***@***.***>:
***@***.*** 
>Please check if the double use of "\clearpage" can cause problems. 
>Inserted between files 0003- and 0100- , once from `10-generate-pdf-manual.sh` and once from `11-helpfile-pdf-manual-header.tex`.
>
>The PDF looks good at this point.
>

@ak-li I'm gonna have a look at it either this evening or tomorrow morning.

**Comment by Mister00X** [comment]
@ak-li I have now had a look at the LaTeX output produced by pandoc (by replacing `.pdf` with `.tex` in `10-generate-pdf-manual.sh`).

The generated LaTeX code in [siduction-manual_en.tex.gz](https://github.com/siduction/sidu-manual/files/8511683/siduction-manual_en.tex.gz) shows no signs of a double `\clearpage` before `\section{Quickstart}` (thats around line 759) but I guess that is because the `\clearpage` in file `11-helpfile-pdf-manual-header.tex` was added as a hook to the `\section{}` macro.

My guess why it's behaving like we want it to is that (La)TeX sets a `\@nobreak` directly after the `\clearpage` macro. (I've read something like that once but can't find it at the moment. I could be completely wrong though.)

For now the generated PDF looks okay to me, the hyperlinks in the file work correctly and I have not found any strange empty pages. Looks good to me :+1:

**Comment by ak-li** [comment]
@Mister00X 
> For now the generated PDF looks okay to me, the hyperlinks in the file work correctly and I have not found any strange empty pages. Looks good to me +1

I test all 1st and 2nd order heading hyperlinks too. They are all fine. Some 2nd order headings do not start with a new page (e.g. 4.5 The fstab). But this is intentional, because several may occur within one file and the file order has priority.

> I have now had a look at the LaTeX output produced by pandoc (by replacing `.pdf` with `.tex` in `10-generate-pdf-manual.sh`).
> The generated LaTeX code in [siduction-manual_en.tex.gz](https://github.com/siduction/sidu-manual/files/8511683/siduction-manual_en.tex.gz) shows no signs of a double `\clearpage` before `\section{Quickstart}` (thats around line 759) but I guess that is because the `\clearpage` in file `11-helpfile-pdf-manual-header.tex` was added as a hook to the `\section{}` macro.
> My guess why it's behaving like we want it to is that (La)TeX sets a `\@nobreak` directly after the `\clearpage` macro. (I've read something like that once but can't find it at the moment. I could be completely wrong though.)

Very good. I am relieved about that.
Now I close this issue.
