### ISSUE TITLE
The wiki disappeared?

### ISSUE THREAD

**Issue by Mister00X** [siduction/sidu-manual#50]
For me both links https://github.com/siduction/sidu-manual/wiki/DE_Home and https://github.com/siduction/sidu-manual/wiki/EN_Home lead to the "main" github page (https://github.com/siduction/sidu-manual). Also the wiki button/tab/whatever disappeared (at least for me).

**Comment by hhl** [comment]
Some one stollen it,  also for me. The button disappeared.

**Comment by hhl** [comment]
It was disabled via settings, don't know what happened!
