### ISSUE TITLE
Mention the `--resizefs` command line option for extending logical volumes

### ISSUE THREAD

**Issue by Mister00X** [siduction/sidu-manual#51]
I noticed that the (german) manual describes the process of enlarging an logical volume in two steps, first enlarge the logical volume and then enlarge the filesystem here https://github.com/siduction/sidu-manual/blob/37941dc3a71e089982668b5800ba25d581012b7c/data/de/0315-part-lvm_de.md?plain=1#L143-L159
`lvextend(8)` is capable of resizing/enlarging the filesystem using `fsadm(8)` when passed the `--resizefs` flag. It is capable of doing this for `ext2`, `ext3`, `ext4`, `ReiserFS` and `XFS` according to its manpage and I know from personal experience that it does support enlarging `ext4` filesystems online (i.e. without unmounting).

What I'm not entirely sure about is, if it supports **online** resizing of the **root** lv/partition.

Should the manual reflect this fact?

If yes we could write something like this:

-----  
Erweitern eines logischen Volumes im Falle eines `ext4` Dateisytems:

Bei Verwendung von `ext4` als Dateisystem kann das logische Volume im gemounteten Zustand vergrößert werden, dies erfolgt mit dem Befehl:
~~~sh
lvextend -L+200g --resizefs /dev/vulcan/spock
~~~
Das auf dem logischen Laufwerk befindliche Dateisystem wird hierbei mit vergrößert.

Ist eine anschließende Überprüfung des Dateisystems gewünscht, so muss das Dateisystem zuerst ausgehängt werden. Aushängen überprüfen und wieder einhängen des Dateisytems erfolgt mit den Befehlen:
~~~sh
umount /media/spock/
e2fsck -f /dev/vulcan/spock
mount /dev/vulcan/spock /media/spock
~~~
> **Achtung**
> Hängen Sie nie Ihr root-Dateisystem im laufenden Betrieb aus!
> Wenn Sie das root-Dateisystem überprüfen wollen, 
> nutzen Sie den Kernel-Kommandozeilen-Parameter `fsck.mode=force` beim Boot-Vorgang.

-------
Thoughts on this?

**Comment by ak-li** [comment]
@Mister00X
ich überarbeite gerade div. Kapitel des Handbuches und werde deine Anregung zusätzlich aufnehmen.
Auch die Warnmeldung; vermutlich an anderer Stelle des Kapitels.

**Comment by ak-li** [comment]
Both variants are now included in the manual. Also the warning message.
The updated manual is already available online.

**Comment by Mister00X** [comment]
Great work
Thanks
