### ISSUE TITLE
Cleanup 10-... and 11-...

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#54]
@Mister00X 
Doppelte und unnötige LaTex Optionen entfernen.
Statische Optionen nach 11-... verlegen.

**Comment by Mister00X** [comment]
> Statische Optionen nach 11-... verlegen.

Eigentlich, denke ich, dass die klügere Variante die ist, alles aus 11-... zu entfernen, was bereits über [pandocs template](https://github.com/jgm/pandoc-templates/blob/master/default.latex) geregelt wird. Sonst haben wir das immer öfter doppelt gemoppelt. Denn einige Optionen die über `-V key=val` gesetzt werden haben Voreinstellungen, wenn die nicht in 10-... gesetzt werden bekommen wir (möglicherweise sowas wie)
```tex
\usepackage[Voreinstellung]{package}

%... 30 Zeilen später eingefügt aus 11-...
\usepackage[Unsere Einstellung]{package}
```
Und es ist nicht gut wenn wir z.B. zweimal das selbe Paket mit unterschiedlichen Optionen laden.

Von einem flüchtigem Blick in 11-... und das Template hab ich jetzt aber nix gefunden, was  aus 11-... raus müsste.

**Comment by ak-li** [comment]
Datei `10-generate-pdf-manual.sh`:
Alle Variablendefinitionen die keine Variablen sind, entfernt und die Werte direkt in den pandoc Befehl eingetragen.
Das Ergebnis:

~~~
pandoc \
     -N --toc --toc-depth=4 \
     -p --pdf-engine=xelatex \
     -H ./11-helpfile-pdf-manual-header.tex \
     --listings \
     --resource-path=./:../data/$langcode/:../data/$langcode/images/:../sys-images/ \
     -V lang=$language \
     -V papersize=$paper \
     -V geometry:textheight=$textheight \
     -V fontsize=12pt \
     -V linkcolor=blue \
     -V nohyphenation=false $LISTE \
     -o ../data/$langcode/pdf/siduction-manual_$langcode.$output_format
~~~

Die Optionen, die LaTex unabhängig vom pandoc Befehl verarbeitet, werden in die Datei `11-helpfile-pdf-manual-header.tex` übertragen.
Das sind die "geometry" Deklarationen, die für alle Sprachen gelten und die Schriften.

~~~
%%% paper settings for all languages
\usepackage{geometry}
  \geometry{portrait}
  \geometry{voffset=6mm}


%%% fonts
\usepackage{fontspec}
  \setmainfont{Liberation Sans}
  \setsansfont{Liberation Sans}
  \setmonofont{Liberation Mono}
~~~

Die mit der "--tex-debug" Option erstellte Datei hat in Zeile 53 diese geometry Definition

~~~
\usepackage[textheight=227mm]{geometry}
~~~

und ab Zeile 100 die zuvor gezeigten Definitionen aus der Datei `11-helpfile-pdf-manual-header.tex`. Es gibt keine doppelten Definitionen mit anderen Werten.
Das erzeugte PDF sieht nach kurzer Inspektion gleich aus. Die letzte Seite ist absolut identisch. Somit stimmen die Abstände von Header Textbereich und Footer überein.

**Comment by Mister00X** [comment]
Okay verstehe, in dem Fall kannst du `\usepackage{geometry}` auch noch aus 11-... entfernen wenn du willst, da durch `-V geometry:textheight=$textheight`in 10-... bereits `\usepackage[textheight=...]{geometry}` eingefügt wird und `\geometry{}` hier dann einfach Optionen hinzufügt.

**Comment by ak-li** [comment]
Änderungen mit commit https://github.com/siduction/sidu-manual/commit/f9242f210c3c45ae1d1d754a5b2d2b86980014f1 eingepflegt und mit commit https://github.com/siduction/sidu-manual/commit/7a573e9d30d8c1098ae83f56ec2fa5bbfeecd814 zu plausiblerem Namen umbenannt.

**Comment by Mister00X** [comment]
Das wird langsam richtig gut :smile:

**Comment by ak-li** [comment]
Freut mich, dann schließe ich das issue.
