### ISSUE TITLE
Separates Menü und Inhaltsseiten HTML mergen

### ISSUE THREAD

**Issue by vinzv** [siduction/sidu-manual#56]
Momentan liefert pandoc im Grunde zwei Dateien:
- Treemenue
- Seiten mit Inhalt
Das führt dazu, dass wir Frames verwenden müssen.

Wenn ich mir `development/22-template-html-manual.html` und `development/31-header-html-menu.html` anschaue, müssten sich diese beiden Seiten doch eigentlich mergen lassen, oder? Also, eigentlich diesen Block in `22-template-html-manual.html` übernehmen:

```
<ul id="treeMenu">
    <li>
	    <a target="_blank" href="https://siduction.org/" alt="Zurück zu siduction.org"><img src="tree-menue-frames_data/logo-manual.png" style="width: 100%"></a>
    </li>
```

Und den darauf folgenden Code (vermutlich aus `30-generate-html-menu.pl`?) auch dorthin schieben lassen.

**Comment by ak-li** [comment]
@vinzv 
Wenn ich das richtig sehe, willst du in allen 50 HTML-Dateien das Menü einbauen. Ist problemlos machbar, aber verstehe den Sinn nicht.

**Comment by vinzv** [comment]
Ganz einfach:
Momentan sind das ja Frames. Frames sind aber einerseits schon seit Jahren deprecated, andererseits funktioniert damit die Darstellung abhängig von der Displaygröße nicht. Ich habe die nur als Notbehelf verwendet um damals möglichst schnell das Manual online zu bekommen.

**Comment by ak-li** [comment]
> Ganz einfach:
> Momentan sind das ja Frames. Frames sind aber einerseits schon seit Jahren deprecated, andererseits funktioniert damit die Darstellung abhängig von der Displaygröße nicht. Ich habe die nur als Notbehelf verwendet um damals möglichst schnell das Manual online zu bekommen.

Das ist schon klar.
Was mich irritiert, ist die Darstellung im Browser. Vermutlich bekommen wir einen riesigen Header mit dem Inhaltsverzeichnis bevor die eigentliche Webseite anfängt.
Ich probiere es einfach mal aus.
Melde mich vermutlich morgen.

**Comment by vinzv** [comment]
Den Header positioniere ich mit CSS an die linke Seite, dann sieht es aus wie bisher.
Ziel ist es, das Menü auf Smartphones ausblenden zu lassen und einen Button einzufügen mit dem es sich einblenden lässt.

**Comment by ak-li** [comment]
Eine Datei mit dem Menü am Anfang. (Screenshot)
Die CSS Formate habe ich über IDs angepasst, da es sonst Überschneidungen mit den Formaten der HTML Inhalte gibt.

Kannst du mir für 

> Den Header positioniere ich mit CSS an die linke Seite, dann sieht es aus wie bisher.

einen Codeschnipsel geben?

[help_de.txt](https://github.com/siduction/sidu-manual/files/8682728/help_de.txt)
Das ist die HTML Seite zum Screenshot. (.txt, weil .html zum Hochladen nicht unterstützt wird. Zum Anschauen wieder umbenennen.)

![Screenshot: HTML_mit_Menue](https://user-images.githubusercontent.com/66441836/168172130-07acea94-5122-477a-ad8b-fbbf0cb169e5.png)

**Comment by ak-li** [comment]
In dieser Datei wurde der CSS Code bereinigt und die vertikalen Abstände in Listen wurden optimiert.
[help-2_de.txt](https://github.com/siduction/sidu-manual/files/8686677/help-2_de.txt)

**Comment by vinzv** [comment]
Ich hab das mal soweit umgebaut:

- Menü links (25% Breite)
- Inhalt rechts (75% Breite)
- Komplette Seite auf 70% Bildschirmbreite
- Menü "sticky", es bleibt beim Scrollen immer sichtbar
- Menü bekommt eine Scrolleiste, wenn es durch Ausklappen zu hoch für den Bildschirm ist

![grafik](https://user-images.githubusercontent.com/74432/168281646-8209b1be-8813-41ec-a753-952e6d4c8f44.png)

Das Anzeigen und Verstecken des Menüs kommt noch. Hier schon mal der aktuelle Stand:
[help-2_de.txt](https://github.com/siduction/sidu-manual/files/8686948/help-2_de.txt)

**Comment by ak-li** [comment]
Design vollständig überarbeitet. Das Handbuch wird nun gleichermaßen gut auf mobilen und stationären Ausgabegeräten dargestellt.
Mit dem Programmaufruf .`/00-generate-manual.pl en de` im Ordner `/development` werden alle HTML und PDF Dateien des Handbuches erzeugt.
