### ISSUE TITLE
dateien gelöscht md2pdf und pandocc-header-pdf.tex

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#6]
Brauchen wir diese dateien nicht mehr?

```
 delete mode 100644 development/pandoc-header-pdf.tex
 delete mode 100755 development/md2pdf
```
```
Fast-forward
 data/de_md/inet-nm-cli_de.md           |  10 +++++-----
 development/md2pdf                     |  44 --------------------------------------------
 development/md2pdf_akli                |  46 ----------------------------------------------
 development/pandoc-header-pdf.tex      | 109 -------------------------------------------------------------------------------------------------------------
 development/pandoc-header-pdf_akli.tex |  88 ----------------------------------------------------------------------------------------
 5 files changed, 5 insertions(+), 292 deletions(-)
 delete mode 100755 development/md2pdf
 delete mode 100755 development/md2pdf_akli
 delete mode 100644 development/pandoc-header-pdf.tex
 delete mode 100644 development/pandoc-header-pdf_akli.tex
```

**Comment by hhl** [comment]
@ak-li 
Ich habe einen pull request geöffnet, wenn es ein Versehen war, kannst du den pullrequest mergen, ansonsten lehne ihn ab

Siehe: https://github.com/siduction/sidu-manual/pull/7

**Comment by ak-li** [comment]
@hhl 
da habe ich wohl Mist gebaut.
Ich wollte die beiden Dateien mit meinen zusammenführen und nicht löschen. Da stekt ja unsere Arbeit drin und die Ergebnisse waren ganz gut.
Habe sie noch auf meinem PC. Ich kümmer mich heute Abend darum das wieder zu berichtigen.
Entschuldige nochmal, wollte dich nicht ärgern.

**Comment by hhl** [comment]
@ak-li, alles ok, wunderte mich nur. Schau Dir ruhig mal den pull request an, ist eine Melange aus allem, incl. Datum automatisch mit Zeitstempel in UTC (so weiß jeder, wann das Manual erstellte wurde) und Autor, so braucht es nur noch %Manual bzw. %Handbuch an oberster Stelle erste Seite.

**Comment by ak-li** [comment]
@hhl 
Die beiden Dateien sind wieder im development-Ordner. Mit allen gemeinsam erstellten Optionen.
