### ISSUE TITLE
New chapter Nala needs review

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#60]
I translated the new file using DeepL
https://github.com/siduction/sidu-manual/blob/WIP/data/en/0707-sys-admin-nala_en.md
and inserted line 17 into
https://github.com/siduction/sidu-manual/blob/WIP/data/en/0700-sys-admin_en.md

Both need review.

**Comment by davydych** [comment]
I've reviewed both files (and updated the wiki), so the issue can be closed.
