### ISSUE TITLE
Collect our scripts

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#64]
As mentioned by a reviewer and devil we should collect our scripts and a short description.

- chroothelper: change to a chroot environment 
- fw-detect: detect firmware which is needed for the system
- sshactivate: start an ssh-server
- sshdectivate: stop an ssh-server
- siduction-irc
- siduction-btrfs
- xfce_icon_add_attrib (Setzen des Atributes metadata::xfce-exe-checksum)
- remove-nonfree
-

**Comment by hhl** [comment]
- siduction-irc: locatet in /usr/bin/, starts an IRC session with following clients depends on the environment, HEXCHAT, IRSSI, KONVERSATION, KVIRC, WEECHAT, XCHAT  and connects to our IRC-channel (#siduction /#siduction-de) on [OFC](https://www.oftc.net/)

**Comment by ak-li** [comment]
Finished with https://github.com/siduction/sidu-manual/commit/5971a34c42d2119eb7da1a8484572b38c8e22ba0

**Comment by ak-li** [comment]
No feedback is also consent. All changes are online with https://github.com/siduction/sidu-manual/commit/e88f944ff14b646b31ce01d3fc0a9d4210fa81c8.
