### ISSUE TITLE
nala changed config

### ISSUE THREAD

**Issue by hhl** [siduction/sidu-manual#66]
Now _**"apt upgrade"**_ is the default, not _**"apt full-upgrade"**_ anymore.

To change it to _**"apt full-upgrade"**_ again, you have to edit _/etc/nala/nala.conf_ and set that option to _**true**_ see below

```
--- /etc/nala/nala.conf 2023-04-03 14:19:37.240971431 +0200
+++ /etc/nala/nala.conf.dpkg-new        2023-09-14 03:59:35.000000000 +0200
@@ -7,12 +7,15 @@
 simple_summary = false
 
 # Set to false to disable auto auto-removing
-auto_remove = false
+auto_remove = true
 
 # Set to false to disable auto updating the package list
 # when running the upgrade command
 auto_update = true
 
+# Set to true to make full-upgrade the default
+full_upgrade = false
+
 # Set to true Nala will list the upgradable packages automatically after `update`
 update_show_packages = false
```

We should mention it in the manual and maybe in the next release notes too.

**Comment by fethomm** [comment]
I will mention it in the RN.

**Comment by ak-li** [comment]
Das würde ich nicht empfehlen:
>  \# Set to false to disable auto auto-removing
> -auto_remove = false
> +auto_remove = true

sondern auto-remove auf false belassen.
Wenn dann purge und auch nur nach manueller Kontrolle.

**Comment by fethomm** [comment]
100% ack

**Comment by hhl** [comment]
ah, das ist das diff von meinem System im Vergleich zur neuen config.

Klar soll autoremove auf false bleiben, sorry, wenn der Post etwas verwirrt.

**Comment by hhl** [comment]
Und hier ist ein erster PR.

https://github.com/siduction/sidu-manual/pull/67

**Comment by ak-li** [comment]
Merge vollzogen:

https://github.com/siduction/sidu-manual/pull/67

en Version folgt in Kürze.

**Comment by ak-li** [comment]
en Übersetzung ist fertig.
Alles in https://github.com/siduction/sidu-manual/tree/WIP/data/de und ../en
