### ISSUE TITLE
md-Dateien für WWW und PDF

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#8]
# Ideensammlung

## Generelle Behandlung der Dateien Status RC3  
   + INFOBEREICH FÜR DIE AUTOREN entfernen.  
   + Horizontale Linien entfernen.

Das Script *md_cleanup_RC3.pl* erledigt das für alle Dateien in dem eingetragenen Ordner.  
Kann man abgeändert auch für die Link verwenden.

## Verwendung als PDF
   + Generell auch im WWW als PDF?
   + Dann eine Masterseite mit einer Menü-Sidebar
   + Nur einzelne PDF-Dateien, wie bekommen wir daraus ein Offline-Handbuch?
   + Oder nur ein großes Dokument (>200 Seiten). Das passt zum Offline-Handbuch. Aber online sinnvoll?
       + Änderung der Referenzen in fast allen Dateien notwendig.
       + Bei Verwendung im WWW ohne PDF sind wahrscheinlich zwei Entwicklungslininen notwendig. **Doppelte Arbeit!**

## Verwendung im WWW
Entscheidend ist, welche Software mit welchem Plugin verwendet wird.
   + Anpassung der internen Link an die Dateistruktur.
   + Eventuell automatische Generierung durch Plugin.
   + TOC erstellen.
   + Frame für TOC bei einzelnen PDF-Dateien.

## Beispiel TOC
Nur wenige Hauptgruppen verwenden.
Unvollständiges Beispiel:
~~~
+ Über das Handbuch
    + Benutzungshinweise
    + siduction Schnellstart
    + Wo es Hilfe gibt
    + Das siduction-Team
    + Copyright
+ ISO's
    + Inhalt und Systemanforderungen
    + Live-Modus
        + Bootoptionen (Bootcodes)
    + Brennen / USB-Medium
+ Installation
    + Installationsoptionen - HD, USB, VM und Cryptroot
    + Partitionierung
    + Der erste Start des Systems
+ Systemadministration
    + Grafik
        + Grafikkarten, Monitore & Treiber
        + Bildschirmauflösung
        + Dual-Monitore
    + Netzwerk
        + Internetverbindung
        + Server
            + LAMP Webserver für Entwickler
            + Samba-Server
        + SSH
        + Firewalls und Datenschutz
    + Paketverwaltung
        + APT der Paketmanager
        + Systemaktualisierung
    + Systemd der System- und Dienste-Manager
    + Systemdjournal
    + CUPS - Drucken mit siduction
    + Schriften und Audio
    + Grub der Bootmanager
~~~

**Comment by hhl** [comment]
Kurz,  fürs WWW hatten wir gedacht die Markdown Seiten zu nehmen und WordPress das rendern zu überlassen, so es dann funktioniert. Mit wenigen Hauptgruppen ist genau richtig!

**Comment by hhl** [comment]
https://github.com/siduction/sidu-manual/issues/9#issuecomment-827170075

Nach kurzem Gespräch im Core-Team:
Gerenderte HTML-Dateien zum Einbinden in WordPress, PDF für download und auf den ISO's

**Comment by ak-li** [comment]
Wird spannend, wie wir das aus einem .md-Stammverzeichnis generieren.
