### ISSUE TITLE
Neue Verzeichnisstruktur für Branch WIP

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#9]
hhl und ich haben verabredet den WIP Brunch von den alten, nicht mehr benötigten, Handbuchdateien zu bereinigen.
Das ist im wesentlichen erledigt.

Jetzt geht es darum die Verzeichnisstruktur für das neue Handbuch festzulegen. In der Folge werde ich dann alle internen Link zu Handbuchseiten und deren Kapiteln und zu den Bildern anpassen.

**Mit der Bitte um eure Meinung zu den vorgeschlagenen Varianten.**

Bisherige Verzeichnisstruktur:
Nach dem Entfernen der nicht mehr benötigten Bestandteile des alten Handbuches befinden sich im Ordner "static/" ausschließlich Bilddateien.
~~~
sidu-manual/
    |--icons/
    |--development/
    |--static/
    |    |--flags/
    |    |--logos/
    |    |--images-common/    (Bilder von noch nicht aktualisierten Dateien)
    |    |--images-de/
    |    |    |--cfdisk-de/
    |    |    |--nstall-hd-de/
    |    |    |--  (usw)
    |    | 
    |    |--images-en
    |    |--  (usw)
    |
    |--data/
         |--de_md/
         |--en
         |--  (usw)
~~~

**Variante 1 neue Verzeichnisstruktur:**
**Alle Daten für die jeweilige Srache, sowohl die .md-Dateien als auch die Bilder, unterhalb /data/<Sprachkürzel>/.**
Innerhalb "data" die sprachspezifischen Ordner, und darin den Ordner "images" mit Unterordnern ohne Sprachkürzel. Nur die Bilddateien sollten ein Sprachkürzel im Namen enthalten, um Konfusion zu vermeiden. Die md-Link zu den Bilder mit nur einem Sprachkürzel vor ".png" lassen sich leicht mit einem Script auf eine andere Sprache anpassen.
Vier Verzeichnisebenen unterhalb "sidu-manual/".
~~~
sidu-manual/
    |--sys-images      (Enthält alle von den .md-Dateien unabhängigen Graphiken.)
    |--development/
    |--data/
         |--de/ 
         |    |--images/
         |        |--cfdisk/
         |        |--install-hd/
         |        |--  (usw)
         |--en/
         |    |--images/
         |        |--  (usw)
         |--  (usw)
~~~

**Variante 2 neue Verzeichnisstruktur:**
**Alle .md-Dateien unterhalb "/data/<Sprachkürzel>/", alle Bilddateien unterhalb "/images/<Sprachkürzel>/".**
Das trennt die Bilder vollständig von den .md-Dateien. 
Drei Verzeichnisebenen unterhalb "sidu-manual/".
~~~
sidu-manual/
    |--sys-images      (Enthält alle von den .md-Dateien unabhängigen Graphiken.)
    |--development/
    |--data/
         |--de/ 
         |--en/
         |--  (usw)
    |--images/
         |--images-de/
         |    |--cfdisk/
         |    |--install-hd/
         |    |--  (usw)
         |
         |--images-en/
         |    |--  (usw)
         |--  (usw)
~~~

**Comment by ak-li** [comment]
ak-li favorisiert Variante 1

**Comment by hhl** [comment]
Variante 1, ist einstimmig von uns allen angenommen, als auch das Rendern von .html  um dann jene in WordPress einzubinden.
PDF zum Download und auf den ISO's,

**Comment by ak-li** [comment]
Änderung der Verzeichnisstruktur erledigt.  
Zusätzlich die internen Link zu anderen Handbuchseiten von .htm auf .md geändert.

Wenn euch systematische Fehler auffallen, bitte hier benachrichtigen.
